package com.slagkryssaren.skcc.android;

import android.content.Context;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.os.Bundle;
import android.support.design.widget.FloatingActionButton;
import android.support.design.widget.Snackbar;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;


import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;

import lecho.lib.hellocharts.gesture.ZoomType;
import lecho.lib.hellocharts.model.Axis;
import lecho.lib.hellocharts.model.Line;
import lecho.lib.hellocharts.model.LineChartData;
import lecho.lib.hellocharts.model.PointValue;
import lecho.lib.hellocharts.model.Viewport;
import lecho.lib.hellocharts.view.Chart;
import lecho.lib.hellocharts.view.LineChartView;

public class StatsActivity extends BaseActivity {

    //SharedPreferences stats;
    SharedPreferences  mPrefs;
    LineChartView chart;
    public List<PointValue> tfliteValues;
    public List<PointValue> tfMobileValues;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mPrefs = getSharedPreferences("chart",MODE_PRIVATE);
        chart = (LineChartView) findViewById(R.id.chart);//new LineChartView(getApplicationContext());
        chart.setInteractive(true);
        chart.setZoomType(ZoomType.HORIZONTAL_AND_VERTICAL);
    }

    @Override
    int getContentViewId() {
        return R.layout.activity_stats;
    }

    @Override
    int getNavigationMenuItemId() {
        return R.id.stats;
    }

    @Override
    protected void onResume() {
        super.onResume();
        //stats = this.getSharedPreferences("stats",Context.MODE_PRIVATE);
        Gson gson = new Gson();
        Type listType = new TypeToken<ArrayList<PointValue>>(){}.getType();
        String tfliteJson = mPrefs.getString("tflite", "");
        String tfMobileJson = mPrefs.getString("tfMobile", "");
        tfliteValues = gson.fromJson(tfliteJson,listType);
        tfMobileValues = gson.fromJson(tfMobileJson,listType);

        float maxNumberOfPoints = Math.max(tfliteValues.size(),tfMobileValues.size());
        //float maxTime = Math.max(tfliteValues.)

        Line lineLite = new Line(tfliteValues).setColor(Color.RED).setCubic(false).setHasLines(false);
        Line lineMobile = new Line(tfMobileValues).setColor(Color.BLUE).setCubic(false).setHasLines(false);
        List<Line> lines = new ArrayList<Line>();
        lines.add(lineLite);
        lines.add(lineMobile);
        LineChartData data = new LineChartData();

        Axis axisX = Axis.generateAxisFromRange(0,maxNumberOfPoints,1).setName("Picture").setAutoGenerated(false);
        Axis axisY = new Axis().setName("Time (ms)").setHasLines(true).setAutoGenerated(true).setMaxLabelChars(4);
        data.setAxisXBottom(axisX);
        data.setAxisYLeft(axisY);
        data.setLines(lines);

        //data.setBaseValue(0);
        chart.setLineChartData(data);
        final Viewport v = new Viewport(chart.getMaximumViewport());
        v.bottom = 300;
        v.top = 1300;
        chart.setMaximumViewport(v);


    }

}
